version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpwd
  mongo-express:
    image: mongo-express
    container_name: my-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpwd
      - ME_CONFIG_MONGODB_SERVER=my-mongo
volumes:
  mongo-data: {}